apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: Backend
spec:
  serviceName: Backend
  replicas: 1
  selector:
    matchLabels:
      app: Backend
  template:
    metadata:
      labels:
        app: Backend
    spec:
      containers:
        - name: domain-monitor-backend
          image: ilyashev1/moniappback:latest
          ports:
            - containerPort: 8081
              name: backend
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "myuser"
            - name: DB_PASSWORD
              value: "mypassword"
            - name: CORS_ALLOWED_ORIGINS
              value: "Frontend"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
            

          
          
