apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: domain-monitor-db
          image: postgres:15 # write the real version we used
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "curl https://raw.githubusercontent.com/danette14/moniappbackDB/DataBase/schema.sql | psql -U myuser -d storedb"]
          env:
            - name: POSTGRES_USER
              value: "myuser"
            - name: POSTGRES_PASSWORD # add secretKeyRef
              value: "mypassword"
            - name: POSTGRES_DB
              value: "storedb"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432  
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: init-script
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi