apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend
spec:
  serviceName: frontend
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: domain-monitor-frontend
          image: ilyashev1/moniappfront:latest
          ports:
            - containerPort: 8080
              name: frontend
          env:
            - name: ENVIRONMENT
              value: "prod"
            - name: BACKEND_HOST
              value: "backend"
            - name: BACKEND_PORT
              value: "8081"
            - name: BACKEND_URL
              value: "backend"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080